config/routes.rb
Rails.application.routes.draw do

  get '/', to: "site#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :companies do
    resources :projects
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :projects
  validates :name, :url, :username, :password, :description, presence: :true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path
    else
      render 'new'
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to @company
    else
      render 'edit'
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    redirect_to companies_path
  end

  private
  def company_params
    params.require(:company).permit(:name, :url, :username, :password, :description)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  #may want to put this method in a static controller (home/splash page)
  def index
    @company = Company.find(params[:company_id])
    @projects = @company.projects
  end

  def new
    @company = Company.find(params[:company_id])
    @project = @company.projects.new
  end

  def create
    company = Company.find(params[:company_id])
    project = company.projects.new(project_params)
    if project.save
      redirect_to company_projects_path
    else
      render 'new'
    end
  end

  def show
    @company = Company.find(params[:company_id])
    @project = @company.projects.find(params[:id])
  end

  def edit
    @company = Company.find(params[:company_id])
    @project = @company.projects.find(params[:id])
  end

  def update
    @company = Company.find(params[:company_id])
    @project = @company.projects.find(params[:id])

    if @project.update(project_params)
      redirect_to company_project_path
    else
      render 'edit'
    end
  end

  def destroy
    company = Company.find(params[:company_id])
    project = company.projects.find(params[:id])

    project.destroy

    redirect_to company_projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :description, :due_date, :level)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    @projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :url %>
  <%= f.text_area :url %>

  <%= f.label :username %>
  <%= f.text_area :username %>

  <%= f.label :password %>
  <%= f.text_area :password %>

  <%= f.button %>
<% end %>

app/views/companies/edit.html.erb
<h2>Edit <%= @company.name %></h2>

<%= render 'form' %>

app/views/companies/index.html.erb
<h2>All Companies</h2>

<ul>
  <% @companies.each do |company| %>
    <li><%= link_to "#{company.name}", company %></li>
    <%= link_to("Delete", company,
        method: :delete, 
        data: { confirm: "Are you sure?" }) 
        %>
  <% end %>
</ul>

<%= link_to "New company?", new_company_path %>

app/views/companies/new.html.erb
<p>Add a Comapny</p>

<%= render 'form' %>

app/views/companies/show.html.erb
<h2><%= @company.name %></h2>

<h3>Website</h3>
<p><%= @company.url %></p>

<h3>Description:</h3>
<p><%= @company.description %></p>

<%= link_to "New Project", new_company_project_path(@company) %>

<%= link_to 'Edit your details', edit_company_path %>

<%= link_to "See this company's listings", company_projects_path(@company) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sourceship</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render("partials/header") %>
    <div class='container'>
      <%= yield %>
    </div>
    <%= render("partials/footer") %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer>
    By Greg Perlman
</footer>

app/views/partials/_header.html.erb
<header>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Sourceship</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Login</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="#">Internships <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Companies</a></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

app/views/projects/_form.html.erb
<%= form_for [@company, @project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :due_date %>
  <%= f.date_field :due_date %>

  <%= f.label :level %>
  <%= f.text_field :level %>

  <%= f.button %>
<% end %>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<h2><%= @company.name %>'s Available Projects</h2>

<ul>
  <% @projects.each do |project| %>
    <li><%= link_to "#{project.name}", company_project_path(@company, project) %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render 'form' %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>

<h3>Description</h3>
<p><%= @project.description %></p>

<h3>Due Date</h3>
<p><%= @project.due_date %></p>

<h3>Completed?</h3>
<p><%= @project.finished %></p>

<h3>Level</h3>
<p><%= @project.level %></p>

<%= link_to "Edit", edit_company_project_path %>

<%= link_to("Delete this project", company_project_path,
        method: :delete, 
        data: { confirm: "Are you sure?" }) %>

app/views/site/all.html.erb
<h2>All Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to "#{project.name}", company_project_path(project.company.id, project.id) %></li>
  <% end %>
</ul>

app/views/site/home.html.erb
<h2>All Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to "#{project.name}", company_project_path(project.company.id, project.id) %></li>
  <% end %>
</ul>